### PR TITLE
Adding functionality to manage operations (create, view list, view si…

### PR DESCRIPTION
**Pull request by lisagitel**
…ngle item detail). No support for OperationsMembers yet.

My first pull request  :)  Getting some initial code for ops into the repo... lots more to do.

### CODE REVIEW

**Comment by lisagitel** [comment]
Yeah, I thought about that and looked at your code (briefly) for examples but didn't find where/how to set the default. Do you recall?

Lisa

________________________________

**Comment by radpin** [comment]
Probably a few ways, but I do something like this:             <input
type="date" class="form-control" required style="width:200px;"
asp-for="Issued">

Where "Issued" is a property on the view model that I bind to. I scooped
that from here:
https://monosar.azurewebsites.net/TrainingOfficer/RecordTrainingOccurrence

**Comment by lisagitel** [comment]
Thanks. I saw that but didn't understand the magic  :) I will shamelessly copy.
BTW I've been trying to name and structure things to go along with what's already there.

________________________________

**Comment by radpin** [comment]
All good code is stolen. :)

**Pull request merged**
